/*
* Automatically generated by 'ng g ng-alain:plugin icon'
*/

import {
  AppstoreOutline,
  ArrowDownOutline,
  BorderLeftOutline,
  BorderRightOutline,
  CloudOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GlobalOutline,
  LockOutline,
  LogoutOutline,
  MenuUnfoldOutline,
  MinusOutline,
  PayCircleOutline,
  PrinterOutline,
  ScanOutline,
  SettingOutline,
  StarOutline,
  TeamOutline,
  ToolOutline,
  UserOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  AppstoreOutline,
  ArrowDownOutline,
  BorderLeftOutline,
  BorderRightOutline,
  CloudOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GlobalOutline,
  LockOutline,
  LogoutOutline,
  MenuUnfoldOutline,
  MinusOutline,
  PayCircleOutline,
  PrinterOutline,
  ScanOutline,
  SettingOutline,
  StarOutline,
  TeamOutline,
  ToolOutline,
  UserOutline
];
